/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package member;

import com.sun.jndi.ldap.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mainform.main_frame;

/**
 *
 * @author Dude
 */
public class Updatemember extends javax.swing.JFrame {

    /**
     * Creates new form addmember
     */
    
    addmember am =new addmember();
    public Updatemember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<String>();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jTextField12 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Membership Form");
        setBounds(new java.awt.Rectangle(250, 120, 860, 545));
        setPreferredSize(new java.awt.Dimension(860, 540));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(865, 525));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CRMEMBERH.jpg"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CRMEMBER.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 75, 170, 110);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UPMEMH.jpg"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UPMEM.jpg"))); // NOI18N
        jButton2.setSelected(true);
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UPMEM.jpg"))); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 200, 170, 110);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DELETEBH.jpg"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DELETEB.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 325, 170, 110);

        jLabel2.setText("Member ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 75, 70, 20);

        jLabel3.setText("Title");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 115, 70, 20);

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 115, 60, 20);

        jLabel5.setText("Marital Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(640, 115, 90, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs.", "Ms." }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(310, 110, 120, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(510, 110, 120, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Married", "Unmarried" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(730, 110, 120, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 70, 120, 30);

        jLabel6.setText("Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 155, 70, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(310, 150, 120, 30);

        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 195, 70, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(310, 190, 120, 30);

        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 155, 60, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(510, 150, 120, 30);

        jLabel9.setText("Phone No.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(640, 155, 90, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(730, 150, 120, 30);

        jLabel10.setText("Email");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(440, 195, 60, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(510, 190, 120, 30);

        jLabel11.setText("Member Type");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(640, 195, 90, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatebutton.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setFocusable(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateh.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(370, 430, 110, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ch3.jpg"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ch2.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(440, 70, 24, 24);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel12.setText("Committee Status");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 32, 100, 24);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "                   ", "President", "Vice President" }));
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(114, 32, 137, 24);

        jLabel13.setText("Main Duty");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 74, 100, 77);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "                      ", "Functions Co-Ordinator", "Event Management" }));
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(114, 100, 137, 24);

        jLabel16.setText("Join Date");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(334, 32, 100, 24);

        jLabel18.setText("Expiration Date");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(334, 105, 100, 14);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(444, 32, 147, 24);
        jPanel2.add(jDateChooser2);
        jDateChooser2.setBounds(444, 100, 147, 24);

        jTextField8.setText("Committee Member");
        jPanel2.add(jTextField8);
        jTextField8.setBounds(120, 100, 127, 20);

        jTabbedPane1.addTab("Committee Member", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel19.setText("Fee-Status");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(116, 49, 104, 23);

        jLabel20.setText("Join Date");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(116, 78, 104, 25);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paid", "Un-Paid" }));
        jPanel3.add(jComboBox7);
        jComboBox7.setBounds(238, 46, 171, 26);
        jPanel3.add(jDateChooser3);
        jDateChooser3.setBounds(238, 78, 171, 25);

        jLabel14.setText("End Date");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(116, 109, 104, 24);
        jPanel3.add(jDateChooser4);
        jDateChooser4.setBounds(238, 109, 171, 24);

        jTextField12.setText("Full Member");
        jPanel3.add(jTextField12);
        jTextField12.setBounds(250, 50, 80, 20);

        jTabbedPane1.addTab("Full Member", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel21.setText("Member ID");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(110, 48, 100, 20);

        jLabel22.setText("Entry Fees");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(109, 109, 101, 22);

        jLabel23.setText("$100 USD ");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(228, 109, 100, 22);

        jTextField11.setForeground(new java.awt.Color(255, 0, 0));
        jTextField11.setText("Auto generated");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField11);
        jTextField11.setBounds(228, 48, 120, 28);

        jTextField9.setText("Casual member");
        jPanel4.add(jTextField9);
        jTextField9.setBounds(230, 50, 79, 20);

        jTabbedPane1.addTab("Casual Member", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(220, 230, 630, 190);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Committee Member", "Full Member", "Casual Member" }));
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(730, 190, 120, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RESET.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setFocusable(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RESET-H.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 430, 110, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home01.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-h.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(790, 461, 65, 53);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setPreferredSize(new java.awt.Dimension(860, 515));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 515);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        addmember am=new addmember();
        am.setVisible(true);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.setVisible(false);
        deletemember dm=new deletemember();
        dm.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            am.st.executeUpdate("Update AddMember set Name='"+jTextField2.getText()+"' where MID ='"+jTextField1.getText()+"'");
            JOptionPane.showMessageDialog(am, "Updated");
        } catch (SQLException ex) {
            Logger.getLogger(Updatemember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
       /*  try{
        ResultSet rs=am.st.executeQuery("select * from AddMember where MID ='"+jTextField1.getText()+"'");
       jTextField2.setText(rs.getString("Name"));
       
       
        
        
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(rootPane, ex);
           
       }
       finally{
       
       }
        
        
        */
        
        
        // TODO add your handling code here:
        try{
            ResultSet rs=am.st.executeQuery("select * from addmember where MID='"+jTextField1.getText()+"' ");
            while (rs.next()){
                jTextField1.setText(rs.getString("MID"));
                jComboBox1.setSelectedItem(rs.getString("Title"));
                jComboBox2.setSelectedItem(rs.getString("Gender"));
                jComboBox3.setSelectedItem(rs.getString("Marital_Status"));
                jTextField2.setText(rs.getString("Name"));
                jTextField4.setText(rs.getString("Address"));
                jTextField5.setText(rs.getString("phone_number"));
                jTextField3.setText(rs.getString("Age"));
                jTextField6.setText(rs.getString("Email_ID"));
                jComboBox6.setSelectedItem(rs.getString("Member_type"));
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        this.setVisible(false);
        main_frame mf = new main_frame();
        mf.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField11.setText(null);
        jTextField12.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updatemember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updatemember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updatemember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updatemember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updatemember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
